name: taobao_dw
version: 1.0.0
config-version: 2
profile: taobao_dw
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]
models:
  taobao_dw:
    staging:
      +materialized: view
    marts:
      +materialized: table
